name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --build-arg ADMIN_PASSWORD=${{secrets.ADMINPASSWORD}} --tag misdevopseucp.azurecr.io/dp-images/sales-app
      
    - uses: azure/docker-login@v2
      with:
        login-server: misdevopseucp.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build . -t misdevopseucp.azurecr.io/dp-images/sales-app --build-arg ADMIN_PASSWORD=${{secrets.ADMINPASSWORD}}
        docker push misdevopseucp.azurecr.io/dp-images/sales-app
